### ISSUE TITLE
Dependency UnityMicrophoneLibrary uses method Module.dynCall_v deprecated in Unity 6

### ISSUE THREAD

**Issue by raphik12** [RageAgainstThePixel/com.utilities.audio#31]
Hello,

In our Unity 6 project using com.openai.unity in a WebGL build, we get a non-blocking error message at launch in the console. It is linked to a dependency, com.utilities.audio, which uses a method not supported anymore in Unity 6.

The call to the Unity 6-deprecated Module.dynCall_v method in https://github.com/RageAgainstThePixel/com.utilities.audio/blob/main/Utilities.Audio/Packages/com.utilities.audio/Runtime/Plugins/WebGL/UnityMicrophoneLibrary.jspre causes the issue.

As I said, it is non-blocking, everything works well since we don't use com.utilities.audio's queryAudioDevices method. So this is just a query to know what you plan to do about this in the short term:
- make it possible not to load this code from com.openai.unity? For instance by selectively removing the use of the UnityMicrophoneLibrary.
- fix the method call?

Best regards

**Comment by StephenHodgson** [comment]
I'll take a look at the documentation and update usages accordingly

**Comment by StephenHodgson** [comment]
@raphik12 please also provide stack traces and logs to get better understanding

**Comment by StephenHodgson** [comment]
[context with fixes](https://discussions.unity.com/t/makedyncall-replacing-dyncall-in-unity-6/1543088)

**Comment by StephenHodgson** [comment]
[workaround](https://discussions.unity.com/t/makedyncall-replacing-dyncall-in-unity-6/1543088/4)

> In order to not to use the deprecated dynCall API, one must enable WebAssembly Table, which is not enabled by default, but it (and WebAssembly 2023 in general) is recommended going forward:

![Image](https://github.com/user-attachments/assets/2a5b729b-0169-4c12-8954-d160fd882714)

**Comment by raphik12** [comment]
Great, thank you!
